### ISSUE TITLE
Broken Docker build due to purity_fb's code

### ISSUE THREAD

**Issue by yuha0** [PureStorage-OpenConnect/pure-exporter#11]
The Dockerfile uses python:3-alpine as the base, which currently uses Python3.7

However, purity_fb is not compatible with Python3.7. The issue I encountered was:

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/pure_exporter.py", line 8, in <module>
    from collectors import FlasharrayCollector
  File "/app/collectors/__init__.py", line 2, in <module>
    from .flashblade import FlashbladeCollector
  File "/app/collectors/flashblade.py", line 3, in <module>
    from purity_fb import PurityFb
  File "/usr/local/lib/python3.7/site-packages/purity_fb/__init__.py", line 1, in <module>
    from .fb_client import PurityFb
  File "/usr/local/lib/python3.7/site-packages/purity_fb/fb_client.py", line 21, in <module>
    from . import purity_fb_1dot9
  File "/usr/local/lib/python3.7/site-packages/purity_fb/purity_fb_1dot9/__init__.py", line 17, in <module>
    from .models.admin import Admin
  File "/usr/local/lib/python3.7/site-packages/purity_fb/purity_fb_1dot9/models/__init__.py", line 128, in <module>
    from .performance_replication import PerformanceReplication
  File "/usr/local/lib/python3.7/site-packages/purity_fb/purity_fb_1dot9/models/performance_replication.py", line 47
    def __init__(self, id=None, name=None, async=None, time=None):
                                               ^
SyntaxError: invalid syntax
```

https://github.com/purestorage/purity_fb_python_client/blob/master/purity_fb/purity_fb_1dot9/models/performance_replication.py#L47

In Python 3.7, async is a reserved keyword.

I am not familiar with purity_fb's code base, so not sure if this could be an easy fix. Can we peg the base image of the exporter to be `python:3.6-alpine` for now? Happy to make a PR if this is an acceptable temporary solution.

**Comment by genegr** [comment]
Purity FB SDK 1.9 is clearly incompatible with Python 3.7. I have opened a ticket to our support to get that issue properly fixed. Meanwhile the FlashBlade Prometheus exporter can be built against SDKs of versions lower than, therefore I have amended the requirements.txt accordingly.
