### ISSUE TITLE
ERROR in app: Exception on /metrics/flasharray [GET]

### ISSUE THREAD

**Issue by ruey-cheng** [PureStorage-OpenConnect/pure-exporter#26]
Hi
I'm using docker quay.io/purestorage/pure-fa-exporter:1.2.3
to collect pure storage flash array(6.0.4) metrics
it works fine before setting pods
after creater pod to test active-dr feature
pure-exporter return error
```
[2021-03-04 03:40:56,834] ERROR in app: Exception on /metrics/flasharray [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/pure_fa_exporter.py", line 70, in route_flasharray
    resp = make_response(generate_latest(registry), 200)
  File "/usr/local/lib/python3.6/site-packages/prometheus_client/exposition.py", line 107, in generate_latest
    for metric in registry.collect():
  File "/usr/local/lib/python3.6/site-packages/prometheus_client/registry.py", line 83, in collect
    for metric in collector.collect():
  File "/app/flasharray_collector/flasharray_collector.py", line 48, in collect
    yield from PodStatusMetrics(self.fa).get_metrics()
  File "/app/flasharray_collector/flasharray_metrics/pod_status_metrics.py", line 43, in get_metrics
    self._status()
  File "/app/flasharray_collector/flasharray_metrics/pod_status_metrics.py", line 29, in _status
    for p in self.fa.get_pods():
  File "/app/flasharray_collector/flasharray_metrics/flasharray.py", line 125, in get_pods
    pdict[p['name']].update(p)
KeyError: 'm20-db2-testpod.undo-demote'
```
Thanks for your reply!

**Comment by genegr** [comment]
Hi,
Thanks for reporting the issue. This is related to an incomplete extraction of all the pods, including those pending for eradication. It is now fixed in version 1.2.4.
The related images are also available on quay.io/purestorage.
